"""Add proper indexing

Revision ID: a02a9b6e7891
Revises: a4a7e274121c
Create Date: 2025-05-15 15:34:04.289664

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'a02a9b6e7891'
down_revision: Union[str, None] = 'a4a7e274121c'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_index(op.f('ix_inventory_changes_product_id'), 'inventory_changes', ['product_id'], unique=False)
    op.create_index(op.f('ix_inventory_changes_timestamp'), 'inventory_changes', ['timestamp'], unique=False)
    op.create_index(op.f('ix_inventory_logs_product_id'), 'inventory_logs', ['product_id'], unique=False)
    op.create_index(op.f('ix_inventory_logs_timestamp'), 'inventory_logs', ['timestamp'], unique=False)
    op.drop_index('idx_product_category', table_name='products')
    op.create_index(op.f('ix_products_category'), 'products', ['category'], unique=False)
    op.drop_index('idx_sales_date', table_name='sales')
    op.create_index('ix_sales_product_date', 'sales', ['product_id', 'sale_date'], unique=False)
    op.create_index(op.f('ix_sales_product_id'), 'sales', ['product_id'], unique=False)
    op.create_index(op.f('ix_sales_sale_date'), 'sales', ['sale_date'], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_sales_sale_date'), table_name='sales')
    op.drop_index(op.f('ix_sales_product_id'), table_name='sales')
    op.drop_index('ix_sales_product_date', table_name='sales')
    op.create_index('idx_sales_date', 'sales', ['sale_date'], unique=False)
    op.drop_index(op.f('ix_products_category'), table_name='products')
    op.create_index('idx_product_category', 'products', ['category'], unique=False)
    op.drop_index(op.f('ix_inventory_logs_timestamp'), table_name='inventory_logs')
    op.drop_index(op.f('ix_inventory_logs_product_id'), table_name='inventory_logs')
    op.drop_index(op.f('ix_inventory_changes_timestamp'), table_name='inventory_changes')
    op.drop_index(op.f('ix_inventory_changes_product_id'), table_name='inventory_changes')
    # ### end Alembic commands ###
