"""Add inventory_changes table

Revision ID: a4a7e274121c
Revises: a4eeb74eaca8
Create Date: 2025-05-15 15:26:31.597134

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'a4a7e274121c'
down_revision: Union[str, None] = 'a4eeb74eaca8'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('inventory_changes', sa.Column('previous_stock', sa.Integer(), nullable=True))
    op.add_column('inventory_changes', sa.Column('new_stock', sa.Integer(), nullable=True))
    op.add_column('inventory_changes', sa.Column('change_amount', sa.Integer(), nullable=True))
    op.drop_column('inventory_changes', 'change')
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('inventory_changes', sa.Column('change', sa.INTEGER(), autoincrement=False, nullable=True))
    op.drop_column('inventory_changes', 'change_amount')
    op.drop_column('inventory_changes', 'new_stock')
    op.drop_column('inventory_changes', 'previous_stock')
    # ### end Alembic commands ###
